services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-network

  springboot-app:
    build: .
    container_name: springboot-container
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://mysql:3306/mydb
      DB_USER: user
      DB_PASS: password
    ports:
      - "8081:8081"
    networks:
      - springboot-network

volumes:
  mysql-data:

networks:
  springboot-network:
